#!/usr/bin/env bash
set -e

pushd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null

echo "Formatting code..."
go fmt ./...
echo "Vetting..."
go vet ./...
echo "Building $(basename "$(pwd)")"
go build ./...
echo "Running tests..."
go test ./...
