---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - v4-draft
  schedule:
    - cron: "35 21 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          cache: true
          go-version-file: "go.mod"

      - name: Vet
        run: go vet -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          cache: true
