---
name: Go Report Card

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  generate_report_card:
    runs-on: ubuntu-latest
    steps:
      - name: Go report card
        uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9 # v1.0
