---
name: Close Stale Issues and PRs
on:
  schedule:
    - cron: "42 6 * * 1"

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@eb5cf3af3ac0a1aa4c9c45633dd1ae542a27a899 # v10.3.0
        with:
          stale-issue-message: >
            This issue has been inactive for one year. Stale issues will be
            closed automatically. If this is still relevant, please comment
            to keep it open.
          stale-pr-message: >
            This pull request has been inactive for one year. Stale PRs will
            be closed automatically. If this is still relevant, please
            comment to keep it open.
          days-before-stale: 365
          days-before-close: 14
          stale-issue-label: stale
          stale-pr-label: stale
