---
name: Unit Tests

on:
  push:
    branches:
      - main
      - v*-draft
  pull_request:
    branches:
      - main
      - v*-draft
  schedule:
    - cron: "15 6 * * 1"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      id-token: write # Required for OIDC token to upload coverage and test results
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            os-flag: ubuntu
          - os: windows-latest
            os-flag: windows
          - os: macos-latest
            os-flag: macos
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: ./.github/actions/setup-go
        with:
          install-gotestsum: 'true'

      - name: Test
        run: gotestsum --junitfile junit.xml --format github-actions --format-icons hivis -- -shuffle on -timeout 600s -v -coverprofile coverage.out -covermode atomic ./...

      - name: Test (race)
        run: gotestsum --format github-actions --format-icons hivis -- -race -shuffle on -timeout 600s -v ./...

      - name: Upload coverage to Codecov
        uses: ./.github/actions/upload-codecov
        with:
          flags: unit,${{ matrix.os-flag }}
          artifact-name: test-results-${{ matrix.os }}
