name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "35 21 * * 3"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build ZeroShot Example
        run: go build -v ./examples/zeroshot/...

      - name: Build Translation Example
        run: go build -v ./examples/translation/...

      - name: Build Summarization Example
        run: go build -v ./examples/summarization/...
